# Generated by Django 3.0.3 on 2021-03-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_type', models.TextField(default='foot')),
                ('working_hours', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('earning', models.IntegerField(default=0)),
                ('current_unfinished_orders', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('delivery_hours', models.TextField()),
                ('complete_time', models.DateTimeField(null=True)),
                ('assign_time', models.DateTimeField(null=True)),
                ('cost', models.TextField(default='foot')),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Courier')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Region')),
            ],
        ),
        migrations.AddField(
            model_name='courier',
            name='regions',
            field=models.ManyToManyField(to='main.Region'),
        ),
    ]
