# Generated by Django 3.0.3 on 2021-03-24 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Courier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Region'),
        ),
    ]
